#!/usr/bin/env bash
# Installs scripts/pre-push.sh as the git pre-push hook for this repo.
# Run once after cloning:  bash scripts/install-hooks.sh
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
HOOK_PATH="$REPO_ROOT/.git/hooks/pre-push"
SCRIPT_PATH="$REPO_ROOT/scripts/pre-push.sh"

chmod +x "$SCRIPT_PATH"

cat > "$HOOK_PATH" <<EOF
#!/usr/bin/env bash
# Auto-generated by scripts/install-hooks.sh — do not edit directly.
bash "$SCRIPT_PATH"
EOF

chmod +x "$HOOK_PATH"
echo "✓ Pre-push hook installed at $HOOK_PATH"
echo "  Every 'git push' will now run backend + frontend tests and security scans."
echo "  To bypass in an emergency (not recommended): git push --no-verify"
